//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `FullPoseEstimationPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FullPoseEstimationPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFullPoseEstimationPub::FullPoseEstimationPub"
};
const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newFullPose"
};
const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name = "newFullPose";

}

bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[0], &iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[2]);
}

::std::string
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompFullPoseEstimationPub::FullPoseEstimationPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceD_newFullPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompFullPoseEstimation::FullPoseEuler iceP_pose;
    istr->readAll(iceP_pose);
    inS.endReadParams();
    this->newFullPose(::std::move(iceP_pose), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ops, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newFullPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationPub::FullPoseEstimationPubPrx::_iceI_newFullPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompFullPoseEstimation::FullPoseEuler& iceP_pose, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_pose);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompFullPoseEstimationPub::FullPoseEstimationPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<FullPoseEstimationPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompFullPoseEstimationPub::FullPoseEstimationPubPrx::ice_staticId()
{
    return FullPoseEstimationPub::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name = "newFullPose";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompFullPoseEstimationPub::upCast(FullPoseEstimationPub* p) { return p; }

void
::IceProxy::RoboCompFullPoseEstimationPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< FullPoseEstimationPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new FullPoseEstimationPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceI_begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& iceP_pose, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_pose);
        result->endWriteParams();
        result->invoke(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::end_newFullPose(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_newFullPose_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_newInstance() const
{
    return new FullPoseEstimationPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_staticId()
{
    return ::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_staticId();
}

RoboCompFullPoseEstimationPub::FullPoseEstimationPub::~FullPoseEstimationPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompFullPoseEstimationPub::upCast(FullPoseEstimationPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFullPoseEstimationPub::FullPoseEstimationPub"
};

}

bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[0], &iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[2]);
}

const ::std::string&
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompFullPoseEstimationPub::FullPoseEstimationPub";
    return typeId;
#else
    return iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceD_newFullPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompFullPoseEstimation::FullPoseEuler iceP_pose;
    istr->read(iceP_pose);
    inS.endReadParams();
    this->newFullPose(iceP_pose, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newFullPose"
};

}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_all, iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompFullPoseEstimationPub_FullPoseEstimationPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newFullPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< FullPoseEstimationPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompFullPoseEstimationPub::FullPoseEstimationPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< FullPoseEstimationPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationPub::_icePatchObjectPtr(FullPoseEstimationPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = FullPoseEstimationPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(FullPoseEstimationPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
