//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `FullPoseEstimationPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __FullPoseEstimationPub_h__
#define __FullPoseEstimationPub_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <FullPoseEstimation.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub;
class FullPoseEstimationPubPrx;

}

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub : public virtual ::Ice::Object
{
public:

    using ProxyType = FullPoseEstimationPubPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void newFullPose(::RoboCompFullPoseEstimation::FullPoseEuler pose, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_newFullPose(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPubPrx : public virtual ::Ice::Proxy<FullPoseEstimationPubPrx, ::Ice::ObjectPrx>
{
public:

    void newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &FullPoseEstimationPubPrx::_iceI_newFullPose, pose, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto newFullPoseAsync(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &FullPoseEstimationPubPrx::_iceI_newFullPose, pose, context);
    }

    ::std::function<void()>
    newFullPoseAsync(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose,
                     ::std::function<void()> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompFullPoseEstimationPub::FullPoseEstimationPubPrx::_iceI_newFullPose, pose, context);
    }

    /// \cond INTERNAL
    void _iceI_newFullPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompFullPoseEstimation::FullPoseEuler&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    FullPoseEstimationPubPrx() = default;
    friend ::std::shared_ptr<FullPoseEstimationPubPrx> IceInternal::createProxy<FullPoseEstimationPubPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompFullPoseEstimationPub
{

using FullPoseEstimationPubPtr = ::std::shared_ptr<FullPoseEstimationPub>;
using FullPoseEstimationPubPrxPtr = ::std::shared_ptr<FullPoseEstimationPubPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< FullPoseEstimationPub>&);
::IceProxy::Ice::Object* upCast(FullPoseEstimationPub*);
/// \endcond

}

}

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub;
/// \cond INTERNAL
::Ice::Object* upCast(FullPoseEstimationPub*);
/// \endcond
typedef ::IceInternal::Handle< FullPoseEstimationPub> FullPoseEstimationPubPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub> FullPoseEstimationPubPrx;
typedef FullPoseEstimationPubPrx FullPoseEstimationPubPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(FullPoseEstimationPubPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompFullPoseEstimationPub
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 * Create a wrapper instance by calling ::RoboCompFullPoseEstimationPub::newCallback_FullPoseEstimationPub_newFullPose.
 */
class Callback_FullPoseEstimationPub_newFullPose_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FullPoseEstimationPub_newFullPose_Base> Callback_FullPoseEstimationPub_newFullPosePtr;

}

namespace IceProxy
{

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub : public virtual ::Ice::Proxy<FullPoseEstimationPub, ::IceProxy::Ice::Object>
{
public:

    void newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_newFullPose(_iceI_begin_newFullPose(pose, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_newFullPose(pose, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_newFullPose(pose, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_newFullPose(pose, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::RoboCompFullPoseEstimationPub::Callback_FullPoseEstimationPub_newFullPosePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_newFullPose(pose, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Context& context, const ::RoboCompFullPoseEstimationPub::Callback_FullPoseEstimationPub_newFullPosePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_newFullPose(pose, context, cb, cookie);
    }

    void end_newFullPose(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompFullPoseEstimationPub
{

class FullPoseEstimationPub : public virtual ::Ice::Object
{
public:

    typedef FullPoseEstimationPubPrx ProxyType;
    typedef FullPoseEstimationPubPtr PointerType;

    virtual ~FullPoseEstimationPub();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void newFullPose(const ::RoboCompFullPoseEstimation::FullPoseEuler& pose, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_newFullPose(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const FullPoseEstimationPub& lhs, const FullPoseEstimationPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const FullPoseEstimationPub& lhs, const FullPoseEstimationPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace RoboCompFullPoseEstimationPub
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 * Create a wrapper instance by calling ::RoboCompFullPoseEstimationPub::newCallback_FullPoseEstimationPub_newFullPose.
 */
template<class T>
class CallbackNC_FullPoseEstimationPub_newFullPose : public Callback_FullPoseEstimationPub_newFullPose_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_FullPoseEstimationPub_newFullPose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FullPoseEstimationPub_newFullPose<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FullPoseEstimationPub_newFullPose<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FullPoseEstimationPub_newFullPose<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FullPoseEstimationPub_newFullPose<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 * Create a wrapper instance by calling ::RoboCompFullPoseEstimationPub::newCallback_FullPoseEstimationPub_newFullPose.
 */
template<class T, typename CT>
class Callback_FullPoseEstimationPub_newFullPose : public Callback_FullPoseEstimationPub_newFullPose_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_FullPoseEstimationPub_newFullPose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T, typename CT> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FullPoseEstimationPub_newFullPose<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T, typename CT> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FullPoseEstimationPub_newFullPose<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T, typename CT> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FullPoseEstimationPub_newFullPose<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompFullPoseEstimationPub::FullPoseEstimationPub::begin_newFullPose.
 */
template<class T, typename CT> Callback_FullPoseEstimationPub_newFullPosePtr
newCallback_FullPoseEstimationPub_newFullPose(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FullPoseEstimationPub_newFullPose<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
