//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `GenericBase.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __GenericBase_h__
#define __GenericBase_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompGenericBase
{

class GenericBase;
class GenericBasePrx;

}

namespace RoboCompGenericBase
{

class HardwareFailedException : public ::Ice::UserExceptionHelper<HardwareFailedException, ::Ice::UserException>
{
public:

    virtual ~HardwareFailedException();

    HardwareFailedException(const HardwareFailedException&) = default;

    HardwareFailedException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    HardwareFailedException(const ::std::string& what) :
        what(::std::move(what))
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(what);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    ::std::string what;
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct TBaseState
{
    float x;
    float correctedX;
    float z;
    float correctedZ;
    float alpha;
    float correctedAlpha;
    float advVx;
    float advVz;
    float rotV;
    bool isMoving;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&, const float&, const float&, const float&, const float&, const float&, const float&, const float&, const bool&> ice_tuple() const
    {
        return std::tie(x, correctedX, z, correctedZ, alpha, correctedAlpha, advVx, advVz, rotV, isMoving);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompGenericBase
{

class GenericBase : public virtual ::Ice::Object
{
public:

    using ProxyType = GenericBasePrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    /**
     * Encapsulates the results of a call to getBasePose.
     */
    struct GetBasePoseResult
    {
        int x;
        int z;
        float alpha;
    };

    virtual void getBasePose(int& x, int& z, float& alpha, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getBasePose(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getBaseState(TBaseState& state, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getBaseState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompGenericBase
{

class GenericBasePrx : public virtual ::Ice::Proxy<GenericBasePrx, ::Ice::ObjectPrx>
{
public:

    void getBasePose(int& x, int& z, float& alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        auto _result = _makePromiseOutgoing<GenericBase::GetBasePoseResult>(true, this, &GenericBasePrx::_iceI_getBasePose, context).get();
        x = _result.x;
        z = _result.z;
        alpha = _result.alpha;
    }

    template<template<typename> class P = ::std::promise>
    auto getBasePoseAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<GenericBase::GetBasePoseResult>>().get_future())
    {
        return _makePromiseOutgoing<GenericBase::GetBasePoseResult, P>(false, this, &GenericBasePrx::_iceI_getBasePose, context);
    }

    ::std::function<void()>
    getBasePoseAsync(::std::function<void(int, int, float)> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        auto _responseCb = [response](GenericBase::GetBasePoseResult&& _result)
        {
            response(_result.x, _result.z, _result.alpha);
        };
        return _makeLamdaOutgoing<GenericBase::GetBasePoseResult>(_responseCb, ex, sent, this, &RoboCompGenericBase::GenericBasePrx::_iceI_getBasePose, context);
    }

    /// \cond INTERNAL
    void _iceI_getBasePose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<GenericBase::GetBasePoseResult>>&, const ::Ice::Context&);
    /// \endcond

    void getBaseState(TBaseState& state, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        state = _makePromiseOutgoing<::RoboCompGenericBase::TBaseState>(true, this, &GenericBasePrx::_iceI_getBaseState, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getBaseStateAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompGenericBase::TBaseState>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompGenericBase::TBaseState, P>(false, this, &GenericBasePrx::_iceI_getBaseState, context);
    }

    ::std::function<void()>
    getBaseStateAsync(::std::function<void(::RoboCompGenericBase::TBaseState)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompGenericBase::TBaseState>(response, ex, sent, this, &RoboCompGenericBase::GenericBasePrx::_iceI_getBaseState, context);
    }

    /// \cond INTERNAL
    void _iceI_getBaseState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGenericBase::TBaseState>>&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    GenericBasePrx() = default;
    friend ::std::shared_ptr<GenericBasePrx> IceInternal::createProxy<GenericBasePrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::RoboCompGenericBase::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompGenericBase::HardwareFailedException& v)
    {
        istr->readAll(v.what);
    }
};

template<>
struct StreamableTraits<::RoboCompGenericBase::TBaseState>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 37;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompGenericBase::TBaseState, S>
{
    static void read(S* istr, ::RoboCompGenericBase::TBaseState& v)
    {
        istr->readAll(v.x, v.correctedX, v.z, v.correctedZ, v.alpha, v.correctedAlpha, v.advVx, v.advVz, v.rotV, v.isMoving);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompGenericBase
{

using GenericBasePtr = ::std::shared_ptr<GenericBase>;
using GenericBasePrxPtr = ::std::shared_ptr<GenericBasePrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompGenericBase
{

class GenericBase;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< GenericBase>&);
::IceProxy::Ice::Object* upCast(GenericBase*);
/// \endcond

}

}

namespace RoboCompGenericBase
{

class GenericBase;
/// \cond INTERNAL
::Ice::Object* upCast(GenericBase*);
/// \endcond
typedef ::IceInternal::Handle< GenericBase> GenericBasePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGenericBase::GenericBase> GenericBasePrx;
typedef GenericBasePrx GenericBasePrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(GenericBasePtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompGenericBase
{

class HardwareFailedException : public ::Ice::UserException
{
public:

    HardwareFailedException() {}
    /**
     * One-shot constructor to initialize all data members.
     */
    explicit HardwareFailedException(const ::std::string& what);
    virtual ~HardwareFailedException() throw();

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymporphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual HardwareFailedException* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

    ::std::string what;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct TBaseState
{
    ::Ice::Float x;
    ::Ice::Float correctedX;
    ::Ice::Float z;
    ::Ice::Float correctedZ;
    ::Ice::Float alpha;
    ::Ice::Float correctedAlpha;
    ::Ice::Float advVx;
    ::Ice::Float advVz;
    ::Ice::Float rotV;
    bool isMoving;
};

}

namespace RoboCompGenericBase
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBasePose.
 */
class Callback_GenericBase_getBasePose_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GenericBase_getBasePose_Base> Callback_GenericBase_getBasePosePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBaseState.
 */
class Callback_GenericBase_getBaseState_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GenericBase_getBaseState_Base> Callback_GenericBase_getBaseStatePtr;

}

namespace IceProxy
{

namespace RoboCompGenericBase
{

class GenericBase : public virtual ::Ice::Proxy<GenericBase, ::IceProxy::Ice::Object>
{
public:

    void getBasePose(::Ice::Int& x, ::Ice::Int& z, ::Ice::Float& alpha, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getBasePose(x, z, alpha, _iceI_begin_getBasePose(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBasePose(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::RoboCompGenericBase::Callback_GenericBase_getBasePosePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBasePose(const ::Ice::Context& context, const ::RoboCompGenericBase::Callback_GenericBase_getBasePosePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBasePose(context, cb, cookie);
    }

    void end_getBasePose(::Ice::Int& x, ::Ice::Int& z, ::Ice::Float& alpha, const ::Ice::AsyncResultPtr& result);
    /// \cond INTERNAL

    void _iceI_end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr&);
    /// \endcond

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBasePose(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void getBaseState(::RoboCompGenericBase::TBaseState& state, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_getBaseState(state, _iceI_begin_getBaseState(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBaseState(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::RoboCompGenericBase::Callback_GenericBase_getBaseStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBaseState(const ::Ice::Context& context, const ::RoboCompGenericBase::Callback_GenericBase_getBaseStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBaseState(context, cb, cookie);
    }

    void end_getBaseState(::RoboCompGenericBase::TBaseState& state, const ::Ice::AsyncResultPtr& result);
    /// \cond INTERNAL

    void _iceI_end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr&);
    /// \endcond

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBaseState(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompGenericBase
{

class GenericBase : public virtual ::Ice::Object
{
public:

    typedef GenericBasePrx ProxyType;
    typedef GenericBasePtr PointerType;

    virtual ~GenericBase();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void getBasePose(::Ice::Int& x, ::Ice::Int& z, ::Ice::Float& alpha, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getBasePose(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void getBaseState(TBaseState& state, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getBaseState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const GenericBase& lhs, const GenericBase& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const GenericBase& lhs, const GenericBase& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompGenericBase::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<typename S>
struct StreamWriter< ::RoboCompGenericBase::HardwareFailedException, S>
{
    static void write(S* ostr, const ::RoboCompGenericBase::HardwareFailedException& v)
    {
        ostr->write(v.what);
    }
};

template<typename S>
struct StreamReader< ::RoboCompGenericBase::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompGenericBase::HardwareFailedException& v)
    {
        istr->read(v.what);
    }
};

template<>
struct StreamableTraits< ::RoboCompGenericBase::TBaseState>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 37;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompGenericBase::TBaseState, S>
{
    static void write(S* ostr, const ::RoboCompGenericBase::TBaseState& v)
    {
        ostr->write(v.x);
        ostr->write(v.correctedX);
        ostr->write(v.z);
        ostr->write(v.correctedZ);
        ostr->write(v.alpha);
        ostr->write(v.correctedAlpha);
        ostr->write(v.advVx);
        ostr->write(v.advVz);
        ostr->write(v.rotV);
        ostr->write(v.isMoving);
    }
};

template<typename S>
struct StreamReader< ::RoboCompGenericBase::TBaseState, S>
{
    static void read(S* istr, ::RoboCompGenericBase::TBaseState& v)
    {
        istr->read(v.x);
        istr->read(v.correctedX);
        istr->read(v.z);
        istr->read(v.correctedZ);
        istr->read(v.alpha);
        istr->read(v.correctedAlpha);
        istr->read(v.advVx);
        istr->read(v.advVz);
        istr->read(v.rotV);
        istr->read(v.isMoving);
    }
};

}
/// \endcond

namespace RoboCompGenericBase
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBasePose.
 */
template<class T>
class CallbackNC_GenericBase_getBasePose : public Callback_GenericBase_getBasePose_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int, ::Ice::Float);

    CallbackNC_GenericBase_getBasePose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GenericBasePrx proxy = GenericBasePrx::uncheckedCast(result->getProxy());
        ::Ice::Int iceP_x;
        ::Ice::Int iceP_z;
        ::Ice::Float iceP_alpha;
        try
        {
            proxy->end_getBasePose(iceP_x, iceP_z, iceP_alpha, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_x, iceP_z, iceP_alpha);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 */
template<class T> Callback_GenericBase_getBasePosePtr
newCallback_GenericBase_getBasePose(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GenericBase_getBasePose<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 */
template<class T> Callback_GenericBase_getBasePosePtr
newCallback_GenericBase_getBasePose(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GenericBase_getBasePose<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBasePose.
 */
template<class T, typename CT>
class Callback_GenericBase_getBasePose : public Callback_GenericBase_getBasePose_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&);

    Callback_GenericBase_getBasePose(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GenericBasePrx proxy = GenericBasePrx::uncheckedCast(result->getProxy());
        ::Ice::Int iceP_x;
        ::Ice::Int iceP_z;
        ::Ice::Float iceP_alpha;
        try
        {
            proxy->end_getBasePose(iceP_x, iceP_z, iceP_alpha, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_x, iceP_z, iceP_alpha, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 */
template<class T, typename CT> Callback_GenericBase_getBasePosePtr
newCallback_GenericBase_getBasePose(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GenericBase_getBasePose<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose.
 */
template<class T, typename CT> Callback_GenericBase_getBasePosePtr
newCallback_GenericBase_getBasePose(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int, ::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GenericBase_getBasePose<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBaseState.
 */
template<class T>
class CallbackNC_GenericBase_getBaseState : public Callback_GenericBase_getBaseState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TBaseState&);

    CallbackNC_GenericBase_getBaseState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GenericBasePrx proxy = GenericBasePrx::uncheckedCast(result->getProxy());
        TBaseState iceP_state;
        try
        {
            proxy->end_getBaseState(iceP_state, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(iceP_state);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 */
template<class T> Callback_GenericBase_getBaseStatePtr
newCallback_GenericBase_getBaseState(const IceUtil::Handle<T>& instance, void (T::*cb)(const TBaseState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GenericBase_getBaseState<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 */
template<class T> Callback_GenericBase_getBaseStatePtr
newCallback_GenericBase_getBaseState(T* instance, void (T::*cb)(const TBaseState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GenericBase_getBaseState<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 * Create a wrapper instance by calling ::RoboCompGenericBase::newCallback_GenericBase_getBaseState.
 */
template<class T, typename CT>
class Callback_GenericBase_getBaseState : public Callback_GenericBase_getBaseState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TBaseState&, const CT&);

    Callback_GenericBase_getBaseState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GenericBasePrx proxy = GenericBasePrx::uncheckedCast(result->getProxy());
        TBaseState iceP_state;
        try
        {
            proxy->end_getBaseState(iceP_state, result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(iceP_state, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 */
template<class T, typename CT> Callback_GenericBase_getBaseStatePtr
newCallback_GenericBase_getBaseState(const IceUtil::Handle<T>& instance, void (T::*cb)(const TBaseState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GenericBase_getBaseState<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState.
 */
template<class T, typename CT> Callback_GenericBase_getBaseStatePtr
newCallback_GenericBase_getBaseState(T* instance, void (T::*cb)(const TBaseState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GenericBase_getBaseState<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
