//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `GenericBase.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GenericBase.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompGenericBase::HardwareFailedException> iceC_RoboCompGenericBase_HardwareFailedException_init("::RoboCompGenericBase::HardwareFailedException");

const ::std::string iceC_RoboCompGenericBase_GenericBase_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGenericBase::GenericBase"
};
const ::std::string iceC_RoboCompGenericBase_GenericBase_ops[] =
{
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompGenericBase_GenericBase_getBasePose_name = "getBasePose";
const ::std::string iceC_RoboCompGenericBase_GenericBase_getBaseState_name = "getBaseState";

}

RoboCompGenericBase::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompGenericBase::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGenericBase::HardwareFailedException";
    return typeId;
}

bool
RoboCompGenericBase::GenericBase::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGenericBase_GenericBase_ids, iceC_RoboCompGenericBase_GenericBase_ids + 2, s);
}

::std::vector<::std::string>
RoboCompGenericBase::GenericBase::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompGenericBase_GenericBase_ids[0], &iceC_RoboCompGenericBase_GenericBase_ids[2]);
}

::std::string
RoboCompGenericBase::GenericBase::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGenericBase::GenericBase::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGenericBase::GenericBase";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceD_getBasePose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    int iceP_x;
    int iceP_z;
    float iceP_alpha;
    this->getBasePose(iceP_x, iceP_z, iceP_alpha, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_x, iceP_z, iceP_alpha);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceD_getBaseState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TBaseState iceP_state;
    this->getBaseState(iceP_state, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_state);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGenericBase_GenericBase_ops, iceC_RoboCompGenericBase_GenericBase_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGenericBase_GenericBase_ops)
    {
        case 0:
        {
            return _iceD_getBasePose(in, current);
        }
        case 1:
        {
            return _iceD_getBaseState(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGenericBase::GenericBasePrx::_iceI_getBasePose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<GenericBase::GetBasePoseResult>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGenericBase_GenericBase_getBasePose_name);
    outAsync->invoke(iceC_RoboCompGenericBase_GenericBase_getBasePose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        },
        [](::Ice::InputStream* istr)
        {
            GenericBase::GetBasePoseResult v;
            istr->readAll(v.x, v.z, v.alpha);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGenericBase::GenericBasePrx::_iceI_getBaseState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGenericBase::TBaseState>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGenericBase_GenericBase_getBaseState_name);
    outAsync->invoke(iceC_RoboCompGenericBase_GenericBase_getBaseState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompGenericBase::GenericBasePrx::_newInstance() const
{
    return ::IceInternal::createProxy<GenericBasePrx>();
}
/// \endcond

const ::std::string&
RoboCompGenericBase::GenericBasePrx::ice_staticId()
{
    return GenericBase::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompGenericBase_GenericBase_getBasePose_name = "getBasePose";

const ::std::string iceC_RoboCompGenericBase_GenericBase_getBaseState_name = "getBaseState";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompGenericBase::HardwareFailedException> iceC_RoboCompGenericBase_HardwareFailedException_init("::RoboCompGenericBase::HardwareFailedException");

}

RoboCompGenericBase::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

RoboCompGenericBase::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompGenericBase::HardwareFailedException::ice_id() const
{
    return "::RoboCompGenericBase::HardwareFailedException";
}

RoboCompGenericBase::HardwareFailedException*
RoboCompGenericBase::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompGenericBase::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompGenericBase::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompGenericBase::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGenericBase::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompGenericBase::upCast(GenericBase* p) { return p; }

void
::IceProxy::RoboCompGenericBase::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< GenericBase>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new GenericBase;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::_iceI_begin_getBasePose(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGenericBase_GenericBase_getBasePose_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGenericBase_GenericBase_getBasePose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGenericBase_GenericBase_getBasePose_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGenericBase_GenericBase_getBasePose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGenericBase::GenericBase::end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGenericBase_GenericBase_getBasePose_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    result->_endReadParams();
}

void IceProxy::RoboCompGenericBase::GenericBase::_iceI_end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGenericBase_GenericBase_getBasePose_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::_iceI_begin_getBaseState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGenericBase_GenericBase_getBaseState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGenericBase_GenericBase_getBaseState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGenericBase_GenericBase_getBaseState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGenericBase_GenericBase_getBaseState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGenericBase::GenericBase::end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGenericBase_GenericBase_getBaseState_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_state);
    result->_endReadParams();
}

void IceProxy::RoboCompGenericBase::GenericBase::_iceI_end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGenericBase_GenericBase_getBaseState_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_state);
    result->_endReadParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompGenericBase::GenericBase::_newInstance() const
{
    return new GenericBase;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompGenericBase::GenericBase::ice_staticId()
{
    return ::RoboCompGenericBase::GenericBase::ice_staticId();
}

RoboCompGenericBase::GenericBase::~GenericBase()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompGenericBase::upCast(GenericBase* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompGenericBase_GenericBase_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGenericBase::GenericBase"
};

}

bool
RoboCompGenericBase::GenericBase::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGenericBase_GenericBase_ids, iceC_RoboCompGenericBase_GenericBase_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompGenericBase::GenericBase::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompGenericBase_GenericBase_ids[0], &iceC_RoboCompGenericBase_GenericBase_ids[2]);
}

const ::std::string&
RoboCompGenericBase::GenericBase::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGenericBase::GenericBase::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGenericBase::GenericBase";
    return typeId;
#else
    return iceC_RoboCompGenericBase_GenericBase_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceD_getBasePose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Int iceP_x;
    ::Ice::Int iceP_z;
    ::Ice::Float iceP_alpha;
    this->getBasePose(iceP_x, iceP_z, iceP_alpha, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_x);
    ostr->write(iceP_z);
    ostr->write(iceP_alpha);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceD_getBaseState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TBaseState iceP_state;
    this->getBaseState(iceP_state, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_state);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompGenericBase_GenericBase_all[] =
{
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompGenericBase::GenericBase::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGenericBase_GenericBase_all, iceC_RoboCompGenericBase_GenericBase_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGenericBase_GenericBase_all)
    {
        case 0:
        {
            return _iceD_getBasePose(in, current);
        }
        case 1:
        {
            return _iceD_getBaseState(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompGenericBase::GenericBase::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< GenericBase, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGenericBase::GenericBase::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< GenericBase, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGenericBase::_icePatchObjectPtr(GenericBasePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = GenericBasePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(GenericBase::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
