[Proxies]
# Proxies for required interfaces
KinovaArm = "kinovaarm:tcp -h localhost -p 0"
KinovaArm1 = "kinovaarm:tcp -h localhost -p 0"
Lidar3D = "lidar3d:tcp -h localhost -p 0"
Lidar3D1 = "lidar3d:tcp -h localhost -p 0"
[Endpoints]
# Endpoints for implements interfaces
Lidar3D = "tcp -p 0"


[Period]
Compute = 100
Emergency = 500

[Component.Debug]
Verbose = true

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
