// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `CameraSimple.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <CameraSimple.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompCameraSimple::HardwareFailedException> iceC_RoboCompCameraSimple_HardwareFailedException_init("::RoboCompCameraSimple::HardwareFailedException");

const ::std::string iceC_RoboCompCameraSimple_CameraSimple_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCameraSimple::CameraSimple"
};
const ::std::string iceC_RoboCompCameraSimple_CameraSimple_ops[] =
{
    "getImage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompCameraSimple_CameraSimple_getImage_name = "getImage";

}

RoboCompCameraSimple::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompCameraSimple::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompCameraSimple::HardwareFailedException";
    return typeId;
}

bool
RoboCompCameraSimple::CameraSimple::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCameraSimple_CameraSimple_ids, iceC_RoboCompCameraSimple_CameraSimple_ids + 2, s);
}

::std::vector<::std::string>
RoboCompCameraSimple::CameraSimple::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompCameraSimple_CameraSimple_ids[0], &iceC_RoboCompCameraSimple_CameraSimple_ids[2]);
}

::std::string
RoboCompCameraSimple::CameraSimple::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCameraSimple::CameraSimple::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompCameraSimple::CameraSimple";
    return typeId;
}

bool
RoboCompCameraSimple::CameraSimple::_iceD_getImage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    inS.readEmptyParams();
    ::RoboCompCameraSimple::TImage iceP_im;
    this->getImage(iceP_im, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_im);
    inS.endWriteParams();
    return true;
}

bool
RoboCompCameraSimple::CameraSimple::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCameraSimple_CameraSimple_ops, iceC_RoboCompCameraSimple_CameraSimple_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCameraSimple_CameraSimple_ops)
    {
        case 0:
        {
            return _iceD_getImage(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompCameraSimple::CameraSimplePrx::_iceI_getImage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraSimple::TImage>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompCameraSimple_CameraSimple_getImage_name);
    outAsync->invoke(iceC_RoboCompCameraSimple_CameraSimple_getImage_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompCameraSimple::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompCameraSimple::CameraSimplePrx::_newInstance() const
{
    return ::IceInternal::createProxy<CameraSimplePrx>();
}

const ::std::string&
RoboCompCameraSimple::CameraSimplePrx::ice_staticId()
{
    return RoboCompCameraSimple::CameraSimple::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompCameraSimple_CameraSimple_getImage_name = "getImage";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompCameraSimple::HardwareFailedException> iceC_RoboCompCameraSimple_HardwareFailedException_init("::RoboCompCameraSimple::HardwareFailedException");

}

RoboCompCameraSimple::HardwareFailedException::HardwareFailedException(const ::std::string& iceP_what) :
    ::Ice::UserException(),
    what(iceP_what)
{
}

RoboCompCameraSimple::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompCameraSimple::HardwareFailedException::ice_id() const
{
    return "::RoboCompCameraSimple::HardwareFailedException";
}

RoboCompCameraSimple::HardwareFailedException*
RoboCompCameraSimple::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompCameraSimple::HardwareFailedException::ice_throw() const
{
    throw *this;
}

void
RoboCompCameraSimple::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompCameraSimple::HardwareFailedException", -1, true);
    Ice::StreamWriter< ::RoboCompCameraSimple::HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompCameraSimple::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompCameraSimple::HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompCameraSimple::upCast(::IceProxy::RoboCompCameraSimple::CameraSimple* p) { return p; }

void
::IceProxy::RoboCompCameraSimple::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCameraSimple::CameraSimple>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompCameraSimple::CameraSimple;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompCameraSimple::CameraSimple::_iceI_begin_getImage(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompCameraSimple_CameraSimple_getImage_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompCameraSimple_CameraSimple_getImage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompCameraSimple_CameraSimple_getImage_name, ::Ice::Idempotent, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompCameraSimple_CameraSimple_getImage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompCameraSimple::CameraSimple::end_getImage(::RoboCompCameraSimple::TImage& iceP_im, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompCameraSimple_CameraSimple_getImage_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompCameraSimple::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_im);
    result->_endReadParams();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompCameraSimple::CameraSimple::_newInstance() const
{
    return new CameraSimple;
}

const ::std::string&
IceProxy::RoboCompCameraSimple::CameraSimple::ice_staticId()
{
    return ::RoboCompCameraSimple::CameraSimple::ice_staticId();
}

RoboCompCameraSimple::CameraSimple::~CameraSimple()
{
}

::Ice::Object* RoboCompCameraSimple::upCast(::RoboCompCameraSimple::CameraSimple* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompCameraSimple_CameraSimple_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCameraSimple::CameraSimple"
};

}

bool
RoboCompCameraSimple::CameraSimple::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCameraSimple_CameraSimple_ids, iceC_RoboCompCameraSimple_CameraSimple_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompCameraSimple::CameraSimple::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompCameraSimple_CameraSimple_ids[0], &iceC_RoboCompCameraSimple_CameraSimple_ids[2]);
}

const ::std::string&
RoboCompCameraSimple::CameraSimple::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCameraSimple::CameraSimple::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompCameraSimple::CameraSimple";
    return typeId;
#else
    return iceC_RoboCompCameraSimple_CameraSimple_ids[1];
#endif
}

bool
RoboCompCameraSimple::CameraSimple::_iceD_getImage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    inS.readEmptyParams();
    ::RoboCompCameraSimple::TImage iceP_im;
    this->getImage(iceP_im, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_im);
    inS.endWriteParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompCameraSimple_CameraSimple_all[] =
{
    "getImage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
RoboCompCameraSimple::CameraSimple::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCameraSimple_CameraSimple_all, iceC_RoboCompCameraSimple_CameraSimple_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCameraSimple_CameraSimple_all)
    {
        case 0:
        {
            return _iceD_getImage(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompCameraSimple::CameraSimple::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompCameraSimple::CameraSimple, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompCameraSimple::CameraSimple::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompCameraSimple::CameraSimple, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompCameraSimple::_icePatchObjectPtr(CameraSimplePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompCameraSimple::CameraSimplePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompCameraSimple::CameraSimple::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
